CREATE OR REPLACE TRIGGER modificari_alumni
    BEFORE DELETE OR UPDATE ON MEMBRI_ALUMNI
 BEGIN
    RAISE_APPLICATION_ERROR(-20005, 'Tabelul MEMBRI_ALUMNI nu poate fi modificat');
 END;
/

DELETE 
FROM MEMBRI_ALUMNI
WHERE ID_MEMBRU = 201;
