CREATE OR REPLACE TRIGGER actualizare_alumni
    BEFORE DELETE ON MEMBRI_ACTIVI
    FOR EACH ROW
 BEGIN 
    INSERT INTO MEMBRI_ALUMNI 
    VALUES(SEQ.NEXTVAL, :OLD.NUME, :OLD.PRENUME, :OLD.EMAIL, :OLD.NR_TEL, :OLD.DATA_ADERARE, SYSDATE);
 END actualizare_alumni;
/

DELETE 
FROM MEMBRI_ACTIVI
WHERE ID_MEMBRU = 142;