CREATE TABLE COMENZI
    (UTILIZATOR VARCHAR2(30),
    NUME_BD VARCHAR2(50),
    EVENIMENT VARCHAR2(20),
    NUME_OBIECT VARCHAR2(30),
    DATA DATE);
CREATE OR REPLACE TRIGGER inregistrare_comenzi
    AFTER CREATE OR DROP OR ALTER ON SCHEMA
 BEGIN
    INSERT INTO COMENZI
    VALUES (SYS.LOGIN_USER, SYS.DATABASE_NAME, SYS.SYSEVENT, SYS.DICTIONARY_OBJ_NAME, SYSDATE);
 END;
/