CREATE TABLE DEPARTAMENTE
(ID_DEPARTAMENT NUMBER(4),
NUME_DEPARTAMENT VARCHAR(30),
ID_DIRECTOR NUMBER(4),
ID_CLUB NUMBER(4),

PRIMARY KEY(ID_DEPARTAMENT));

CREATE TABLE MEMBRI_ACTIVI
(ID_MEMBRU NUMBER(4),
NUME VARCHAR(20) NOT NULL,
PRENUME VARCHAR(20),
EMAIL CHAR(30),
NR_TEL VARCHAR(15),
DATA_ADERARE DATE DEFAULT SYSDATE,
ID_DEPARTAMENT NUMBER(4),

PRIMARY KEY(ID_MEMBRU),
CONSTRAINT FK_ID_DEPARTAMENT FOREIGN KEY(ID_DEPARTAMENT)
REFERENCES DEPARTAMENTE(ID_DEPARTAMENT),
CONSTRAINT U_NUME_PRENUME UNIQUE(NUME, PRENUME),
CONSTRAINT U_EMAIL UNIQUE(EMAIL));

CREATE TABLE PROIECT
(ID_PROIECT NUMBER(4),
TITLU_PROIECT VARCHAR(30),
SCOP VARCHAR(20),
DATA_DESFASURARE DATE,
REPREZENTANT_PROIECTE NUMBER(4),
REPREZENTANT_PR NUMBER(4),
REPREZENTANT_HR NUMBER(4),
REPREZENTANT_MK NUMBER(4),

PRIMARY KEY(ID_PROIECT),
CONSTRAINT FK_REPREZENTANT_PROIECTE FOREIGN KEY(REPREZENTANT_PROIECTE)
REFERENCES MEMBRI_ACTIVI(ID_MEMBRU),
CONSTRAINT FK_REPREZENTANT_PR FOREIGN KEY(REPREZENTANT_PR)
REFERENCES MEMBRI_ACTIVI(ID_MEMBRU),
CONSTRAINT FK_REPREZENTANT_HR FOREIGN KEY(REPREZENTANT_HR)
REFERENCES MEMBRI_ACTIVI(ID_MEMBRU),
CONSTRAINT FK_REPREZENTANT_MK FOREIGN KEY(REPREZENTANT_MK)
REFERENCES MEMBRI_ACTIVI(ID_MEMBRU));

ALTER TABLE PROIECT
ADD(ID_CLUB NUMBER(4));

ALTER TABLE PROIECT
ADD CONSTRAINT FK_PROIECT_CLUBURI
FOREIGN KEY (ID_CLUB)
REFERENCES CLUBURI(ID_CLUB);

CREATE TABLE TASK 
(ID_TASK NUMBER(4),
TITLU_TASK VARCHAR(30) NOT NULL,
STATUS VARCHAR(20),
DEADLINE DATE,
ID_PROIECT NUMBER(4),
ID_MEMBRU NUMBER(4),

PRIMARY KEY(ID_TASK),
CONSTRAINT FK_ID_PROIECT FOREIGN KEY(ID_PROIECT)
REFERENCES PROIECT(ID_PROIECT),
CONSTRAINT FK_ID_MEMBRU FOREIGN KEY(ID_MEMBRU)
REFERENCES MEMBRI_ACTIVI(ID_MEMBRU)
);

CREATE TABLE PACHET_DE_FINANTARE
(ID_PACHET NUMBER(2),
NUME_PACHET VARCHAR(20),
PROMOVARE_ONLINE VARCHAR(5),
AFISARE_SIGLA VARCHAR(5),
ROLL_UP VARCHAR(5),
DISTRIBUIRE_FLYERE VARCHAR(5),
COMUNICAT_PRESA VARCHAR(5),
PROMOVARE_SITE VARCHAR(5),
INVITARE_REPREZENTANT VARCHAR(5),
ALEGE_PROIECT VARCHAR(5),

PRIMARY KEY(ID_PACHET),
CONSTRAINT U_NUME_PACHET UNIQUE(NUME_PACHET));

CREATE TABLE SPONSORI
(ID_SPONSOR NUMBER(4),
NUME_SPONSOR VARCHAR(30),
ID_PACHET NUMBER(2),
SUMA NUMBER(5),
ID_PROIECT NUMBER(4),

PRIMARY KEY(ID_SPONSOR),
CONSTRAINT FK_ID_PACHET FOREIGN KEY(ID_PACHET)
REFERENCES PACHET_DE_FINANTARE(ID_PACHET),
CONSTRAINT CK_SUMA CHECK(SUMA > 0),
CONSTRAINT FK_ID_PROIECT_SPONSORI FOREIGN KEY(ID_PROIECT)
REFERENCES PROIECT(ID_PROIECT));

CREATE TABLE FILIALE
(ID_FILIALA NUMBER(4),
NUME_FILIALA VARCHAR(30),

PRIMARY KEY(ID_FILIALA),
CONSTRAINT U_NUME_FILIALA UNIQUE(NUME_FILIALA));
CREATE TABLE CLUBURI
(ID_CLUB NUMBER(4),
NUME_CLUB VARCHAR(20),
ID_FILIALA NUMBER(4),

PRIMARY KEY(ID_CLUB),
CONSTRAINT U_NUME_CLUB UNIQUE(NUME_CLUB));

CREATE TABLE MEMBRI_ALUMNI
(ID_MEMBRU NUMBER(4),
NUME VARCHAR(20) NOT NULL,
PRENUME VARCHAR(20),
EMAIL CHAR(30),
NR_TEL VARCHAR(15),
DATA_ADERARE DATE,
DATA_RETRAGERE DATE,

PRIMARY KEY(ID_MEMBRU),
CONSTRAINT U_NUME_PRENUME_ALUMNI UNIQUE(NUME, PRENUME),
CONSTRAINT U_EMAIL_ALUMNI UNIQUE(EMAIL));

ALTER TABLE DEPARTAMENTE
ADD CONSTRAINT FK_CLUB_ID  FOREIGN KEY(ID_CLUB) 
REFERENCES CLUBURI(ID_CLUB);
