INSERT INTO CLUBURI
VALUES(SEQ.NEXTVAL, 'Iasi', 1);

INSERT INTO CLUBURI
VALUES(SEQ.NEXTVAL, 'Vaslui', 1);

INSERT INTO CLUBURI
VALUES(SEQ.NEXTVAL, 'Roman', 1);

INSERT INTO DEPARTAMENTE
VALUES(SEQ.NEXTVAL, 'Scriere de Proiecte', 10, 2);

INSERT INTO DEPARTAMENTE
VALUES(SEQ.NEXTVAL, 'Relatii Publice', 11, 2);

INSERT INTO DEPARTAMENTE
VALUES(SEQ.NEXTVAL, 'Resurse Umane', 12, 2);

INSERT INTO DEPARTAMENTE
VALUES(SEQ.NEXTVAL, 'Marketing', 13, 2);

INSERT INTO DEPARTAMENTE
VALUES(SEQ.NEXTVAL, 'Consiliu Executiv', 14, 2);

INSERT INTO MEMBRI_ACTIVI(ID_MEMBRU, NUME, PRENUME, DATA_ADERARE, ID_DEPARTAMENT)
VALUES(SEQ.NEXTVAL, 'Baciu', 'Marius', '13-JUN-21', 5);

INSERT INTO MEMBRI_ACTIVI(ID_MEMBRU, NUME, PRENUME, DATA_ADERARE, ID_DEPARTAMENT)
VALUES(SEQ.NEXTVAL, 'Craciun', 'Dana', '16-MAR-22', 6);

INSERT INTO MEMBRI_ACTIVI(ID_MEMBRU, NUME, PRENUME, DATA_ADERARE, ID_DEPARTAMENT)
VALUES(SEQ.NEXTVAL, 'Cirlan', 'Denisa', '22-JAN-21', 7);

INSERT INTO MEMBRI_ACTIVI(ID_MEMBRU, NUME, PRENUME, DATA_ADERARE, ID_DEPARTAMENT)
VALUES(SEQ.NEXTVAL, 'Ion', 'Marian', '17-MAR-22', 8);

INSERT INTO MEMBRI_ACTIVI(ID_MEMBRU, NUME, PRENUME, DATA_ADERARE, ID_DEPARTAMENT)
VALUES(SEQ.NEXTVAL, 'Popescu', 'Sara', '10-MAY-21', 9);

INSERT INTO MEMBRI_ACTIVI(ID_MEMBRU, NUME, PRENUME, DATA_ADERARE, ID_DEPARTAMENT)
VALUES(SEQ.NEXTVAL, 'Vlad', 'Andreea', '16-APR-23', 5);

INSERT INTO MEMBRI_ACTIVI(ID_MEMBRU, NUME, PRENUME, DATA_ADERARE, ID_DEPARTAMENT)
VALUES(SEQ.NEXTVAL, 'Dinu', 'Tudor', '22-JUN-23', 6);

INSERT INTO MEMBRI_ACTIVI(ID_MEMBRU, NUME, PRENUME, DATA_ADERARE, ID_DEPARTAMENT)
VALUES(SEQ.NEXTVAL, 'Pinzaru', 'Alex', '23-JUL-23', 7);

INSERT INTO MEMBRI_ACTIVI(ID_MEMBRU, NUME, PRENUME, DATA_ADERARE, ID_DEPARTAMENT)
VALUES(SEQ.NEXTVAL, 'Gologan', 'Ianis', '13-DEC-22', 8);

INSERT INTO MEMBRI_ACTIVI(ID_MEMBRU, NUME, PRENUME, DATA_ADERARE, ID_DEPARTAMENT)
VALUES(SEQ.NEXTVAL, 'Grigore', 'Teodora', '19-MAY-20', 9);

INSERT INTO MEMBRI_ACTIVI(ID_MEMBRU, NUME, PRENUME, DATA_ADERARE, ID_DEPARTAMENT)
VALUES(SEQ.NEXTVAL, 'Valeanu', 'Teodora', '22-JAN-23', 5);

INSERT INTO MEMBRI_ACTIVI(ID_MEMBRU, NUME, PRENUME, DATA_ADERARE, ID_DEPARTAMENT)
INSERT INTO MEMBRI_ACTIVI(ID_MEMBRU, NUME, PRENUME, DATA_ADERARE, ID_DEPARTAMENT)
VALUES(SEQ.NEXTVAL, 'Perju', 'Andreea', '23-JUL-23', 7);

INSERT INTO MEMBRI_ACTIVI(ID_MEMBRU, NUME, PRENUME, DATA_ADERARE, ID_DEPARTAMENT)
VALUES(SEQ.NEXTVAL, 'Gheorghe', 'Flavia', '12-JUL-22', 8);

INSERT INTO MEMBRI_ACTIVI(ID_MEMBRU, NUME, PRENUME, DATA_ADERARE, ID_DEPARTAMENT)
VALUES(SEQ.NEXTVAL, 'Feraru', 'Catalina', '22-MAR-20', 9);

INSERT INTO MEMBRI_ALUMNI(ID_MEMBRU, NUME, PRENUME, DATA_ADERARE, DATA_RETRAGERE)
VALUES(SEQ.NEXTVAL, 'Anton', 'Florin', '14-APR-19', '16-SEP-22');

INSERT INTO MEMBRI_ALUMNI(ID_MEMBRU, NUME, PRENUME, DATA_ADERARE, DATA_RETRAGERE)
VALUES(SEQ.NEXTVAL, 'Gheorghe', 'Andrei', '14-MAY-18', '17-OCT-21');

INSERT INTO MEMBRI_ALUMNI(ID_MEMBRU, NUME, PRENUME, DATA_ADERARE, DATA_RETRAGERE)

INSERT INTO MEMBRI_ALUMNI(ID_MEMBRU, NUME, PRENUME, DATA_ADERARE, DATA_RETRAGERE)
VALUES(SEQ.NEXTVAL, 'Dan', 'Gicu', '4-Feb-20', '28-SEP-22');

INSERT INTO MEMBRI_ALUMNI(ID_MEMBRU, NUME, PRENUME, DATA_ADERARE, DATA_RETRAGERE)
VALUES(SEQ.NEXTVAL, 'Alexe', 'Mihai', '14-APR-20', '8-MAY-22');

INSERT INTO PROIECT
VALUES(SEQ.NEXTVAL, 'Cariere', 'Informativ', '22-OCT-23', 117, 118, 119, 120,4);

INSERT INTO PROIECT
VALUES(SEQ.NEXTVAL, 'Job Almanac', 'Informativ', '23-APR-23', 122, 123, 124, 125,4);

INSERT INTO PROIECT
VALUES(SEQ.NEXTVAL, 'Arta n Dar', 'Caritabil', '20-DEC-23', 127, 128, 129, 130,4);

INSERT INTO PROIECT
VALUES(SEQ.NEXTVAL, 'RomanMUN', 'Academic', '6-AUG-23', 132, 133, 134, 141,4);

INSERT INTO SPONSORI
VALUES(SEQ.NEXTVAL, 'FabLab Iasi', 3, 3000, 61);

INSERT INTO SPONSORI
VALUES(SEQ.NEXTVAL, 'Plantagro', 3, 2000, 146);

INSERT INTO SPONSORI
VALUES(SEQ.NEXTVAL, 'Adobe', 2, 2000, 143);

INSERT INTO SPONSORI
VALUES(SEQ.NEXTVAL, 'Bitdefender', 2, 1500, 143);

INSERT INTO SPONSORI
VALUES(SEQ.NEXTVAL, 'Hiccup', 3, 3000, 83);

INSERT INTO SPONSORI
VALUES(SEQ.NEXTVAL, 'Miaunel', 1, 500, 82);

INSERT INTO SPONSORI
VALUES(SEQ.NEXTVAL, 'Blanca', 1, 300, 82);

INSERT INTO SPONSORI
VALUES(SEQ.NEXTVAL, 'Centrul de Afaceri', 3, 4000, 109);

INSERT INTO SPONSORI
VALUES(SEQ.NEXTVAL, 'Rotaru', 2, 3000, 145);

INSERT INTO SPONSORI
VALUES(SEQ.NEXTVAL, 'Hiccup', 2, 2000, 111);

INSERT INTO SPONSORI
VALUES(SEQ.NEXTVAL, 'OpportuniTool', 3, 2500, 144);

INSERT INTO TASK
VALUES(SEQ.NEXTVAL, 'Formular Inscriere', 'Realizat', '5-AUG-23', 61, 17);

INSERT INTO TASK
VALUES(SEQ.NEXTVAL, 'Cautat Joculete', 'In curs', '5-SEP-23', 110, 101);

INSERT INTO TASK
VALUES(SEQ.NEXTVAL, 'Contactat Speakeri', 'Realizat', '5-JUL-23', 82, 24);

INSERT INTO TASK
VALUES(SEQ.NEXTVAL, 'Contactat Speakeri', 'Realizat', '5-MAR-23', 83, 29);

INSERT INTO TASK
VALUES(SEQ.NEXTVAL, 'Cautat Sala', 'Neinceput', '5-DEC-23', 109, 97);

INSERT INTO TASK
VALUES(SEQ.NEXTVAL, 'Cautat Film', 'Realizat', '5-JUN-23', 111, 104);

INSERT INTO TASK
VALUES(SEQ.NEXTVAL, 'Mapa de Proiect', 'Realizat', '5-OCT-23', 143, 117);

INSERT INTO TASK
VALUES(SEQ.NEXTVAL, 'Cautat Speakeri', 'Realizat', '5-APR-23', 144, 122);

INSERT INTO TASK
VALUES(SEQ.NEXTVAL, 'Cautat Colinde', 'Neinceput', '5-DEC-23', 145, 127);

INSERT INTO TASK
VALUES(SEQ.NEXTVAL, 'Contactat Scoala', 'Realizat', '5-AUG-23', 146, 141);